FROM golang:alpine AS builder

WORKDIR /usr/src/app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server

FROM scratch

WORKDIR /

COPY --from=builder /usr/src/app/server /server

EXPOSE 8080

CMD ["/server"]