FROM ubuntu:16.04

WORKDIR /usr/src/app

COPY . .

RUN apt-get update && \
    apt-get -y install curl && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash && \
    apt-get -y install nodejs && \
    npm install && \
    npm run build && \
    npm install -g serve && \
    useradd --system appuser && \
    apt-get purge -y --auto-remove curl && \
    rm -rf /var/lib/apt/lists/*

USER appuser

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "build"]