FROM node:16-alpine

WORKDIR /usr/src/app

COPY . .

RUN npm install && \
    npm run build && \
    npm install -g serve && \
    adduser -S appuser && \
    rm -rf /var/cache/apk/* && \
    rm -rf node_modules

USER appuser

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "build"]