FROM node:16-alpine as builder

WORKDIR /usr/src/app

COPY . .

RUN npm install && \
    npm run build

FROM node:16-alpine

WORKDIR /usr/src/app

RUN npm install -g serve && \
    adduser -S appuser && \
    rm -rf /var/cache/apk/*

COPY --from=builder /usr/src/app/build ./build

USER appuser

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "build"]